### ISSUE TITLE
Feature Request: Ability to stay in recurring events

### ISSUE THREAD

**Issue by sippeangelo** [GuardKenzie/landra#3]
I noticed that for daily events, the fact that you're kicked out of the party every day could get a bit cumbersome if your absence is the exception. It would be nice if you had a choice when joining an event if you want to "**Join (this event)**" or "**Join (this and following events)**" similar to Google Calendar!

**Comment by GuardKenzie** [comment]
I will take a look at this soon but it might take a while, sorry.

**Comment by sippeangelo** [comment]
No rush! I appreciate your work!

**Comment by GuardKenzie** [comment]
Sorry about the time this took. I have implemented this with #4

**Comment by sippeangelo** [comment]
Lovely work, thank you!
