### ISSUE TITLE
Landra does apply time_offset twice when using /announce function

### ISSUE THREAD

**Issue by Matgoeth** [GuardKenzie/landra#5]
From what I can see in generateEventsList even though List is applying time offset it is actually storing it in another variable called offset_date:
https://github.com/GuardKenzie/landra/blob/f4012f98814dc8419eccec0a629bf5fb7ddd9a79/backend/misc.js#L533
However announce function is modifying event itself by adding time offset and storing it in original event date:
https://github.com/GuardKenzie/landra/blob/f4012f98814dc8419eccec0a629bf5fb7ddd9a79/backend/misc.js#L36
This causes bug that if there is any timezone set in config then it'll be shown differently in /announce and /post

**Comment by GuardKenzie** [comment]
Wow! Good catch and fantastic bug report. This has been fixed in 0a0b563. I'll push it to live later tonight.

**Comment by Matgoeth** [comment]
Much obliged, @GuardKenzie!

Actually it was just bugged on my server, so I had a quick look, nothing that you wouldn't spot while migrating to getOffsetTime(event) ;) Thanks, though!
